package com.iktpreobuka.elektronskidnevnik.enumeration;

public enum EGradeType {

	KONTROLNI_ZADATAK, PISMENI_ZADATAK, USMENI_ODGOVOR, TEST, AKTIVNOST_NA_CASU, 
	PRAKTICNI_RAD, OSTALO, ZAKLJUCNA_OCENA_PRVO_POLUGODISTE, 
	ZAKLJUCNA_OCENA_DRUGO_POLUGODISTE, ZAKLJUCNA_OCENA_KONACNA 
}
